name: Mark stale issues and pull requests

on:
  workflow_dispatch:

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 10
        days-before-close: 10

  cycle-weekly-close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: weekly-issue-closure
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: 'no-issue-activity'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

